version: 2

sources:
  - name: raw
    schema: raw
    description: "Raw Telegram data loaded from JSON files"

    tables:
      - name: telegram_messages
        description: "Raw Telegram messages scraped from public medical channels"

        loaded_at_field: ingestion_timestamp

        freshness:
          warn_after:
            count: 24
            period: hour
          error_after:
            count: 48
            period: hour
